layout: sidebar
style: light

plugins:
  - jekyll-octicons
  - jekyll-github-metadata
  - jemoji

permalink: /:year/:month/:day/:title/

defaults:
  -
    scope:
      path: "" # an empty string here means all files in the project
      type: "posts"
    values:
      layout: "post"

projects:
  sort_by: pushed
  # sort_by options:
  #   - pushed
  #   - stars
  limit: 6
  exclude:
    forks: true
    projects:
     - beg_stud_lit
     - nosetest-tracker

social_media:
  # behance: your_username
  # dribbble: your_username
  # facebook: your_username
  # hackerrank: your_username
  # instagram: your_username
  # keybase: your_username
  linkedin: jesper-hallborg-aa1b74a8
  # medium: your_username
  # stackoverflow: your_user_id
  # telegram: your_username
  # twitter: your_username
  # unsplash: your_username
  # vk: your_username
  # website: http://your_website_url
  # youtube: your_username
topics:
  - name: Clean Code
    web_url: https://blog.cleancoder.com/
    image_url: https://blog.cleancoder.com/assets/clean_code_72_color.png

  - name: Scala
    web_url: https://scala-lang.org/
    image_url: https://www.scala-lang.org/resources/img/frontpage/scala-spiral.png

  - name: Cucumber
    web_url: https://cucumber.io/
    image_url: https://pbs.twimg.com/profile_images/532924342523273216/jasVAxyJ_400x400.png
